services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shorturl
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: shorturl
      SERVER_PORT: 8080
      BASE_URL: http://localhost:8080/
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
